name: Publish to Docker Hub

on:
  push:
    branches:
      - main
    paths-ignore:
      - "*.md"
  workflow_dispatch:

jobs:
  build-and-push-to-docker-hub:
    name: Build and Push to Docker Hub
    runs-on: ubuntu-24.04
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          # TODO: support multiple Dockerfiles
          file: ./Dockerfiles/alpine.Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/postgres-e2econtainer:15-alpine3.20-hll2.18
          build-args: |
            POSTGRES_VERSION=15
            ALPINE_VERSION=3.20
            HLL_VERSION=2.18
